### ISSUE TITLE
Especificación formato GeoWE Project

### ISSUE THREAD

**Issue by jmmluna** [sigdeletras/qgis2geowe#2]
Hola @sigdeletras,

gracias al desarrollo de tu script he detectado que en la documentación del formato de **proyecto GeoWE** no se detalla completamente la estructura del formato. Para el correcto funcionamiento del formato el contenido de la estructura del proyecto estará formada por un único archivo llamado **geowe-project.prj**. No debe existir estructura de directorios ni subdirectorios para evitar complejidad al formato. Es cierto que en esta primera versión del formato para la carga desde fichero se permiten directorios e incluso cualquier nombre de fichero, pero para la carga de proyecto por URL si que se tiene en cuenta lo que te he comentado. Por tanto, la estructura de formato válida es la que se muestra en la siguiente figura:

![formato-proyecto-geowe](https://cloud.githubusercontent.com/assets/17873390/23458708/9b0ac256-fe7d-11e6-823e-cd4dfc00b11b.png)

Se actualizará la información de la especificación del formato y se validará correctamente para la carga desde fichero al igual que para la carga por URL

Muchas gracias!!

**Comment by sigdeletras** [comment]
Hola @jmmluna 

Ha sido añadida un línea de código para no eliminar la estructura de directorios y subdirectorios en el zip del proyecto. Igualmente el proyecto prj se llamará siempre **geowe-project.prj** tal y como indica la especificación.

Gracias por tu colaboración
